### ISSUE TITLE
VS2017

### ISSUE THREAD

**Issue by RealDotNetDave** [GuidoNeele/VersioningControlledBuild#2]
Do you have plans to release a version for Visual Studio 2017. I am having strange issues like not able to do a build more than once.

David McCarter

**Comment by GuidoNeele** [comment]
Hi David,

The vs 2017 version is already online 😉. Check the vs marketplace.

**Comment by RealDotNetDave** [comment]
I have that one installed.

**Comment by tedebus** [comment]
Hi, same behavior for me on VS2015 Community. First time it works fine, then the VCB menu shows only "configure" and "About".
1.2.1.0 installed

**Comment by GuidoNeele** [comment]
Hi tedebus, a file needs to be selected or opened for the menu buttons to be visible. If all files are closed and no files are selected in the solutions explorer then the menu will be smaller. The actions are being shown or hidden based on the status of Visual Studio windows (mainly the solution explorer window). It's not something the extension controls but it's Visual Studio itself.

The code below indicates when the buttons need to be shown or hidden. I don't believe I can add more flags (contexts) that would solve this behavior.
```
VersioningControlledBuild/BuildAutoIncrement/VcbCommandPackage.vsct
...
<VisibilityConstraints>
    <VisibilityItem guid="guidVcbCommandSet" id="GuiCommandId" context="UICONTEXT_SolutionHasSingleProject" />
    <VisibilityItem guid="guidVcbCommandSet" id="GuiCommandId" context="UICONTEXT_SolutionHasMultipleProjects" />
    <VisibilityItem guid="guidVcbCommandSet" id="GuiCommandId" context="UICONTEXT_SolutionBuilding" />
    <VisibilityItem guid="guidVcbCommandSet" id="BuildVersionsCommandId" context="UICONTEXT_SolutionHasSingleProject" />
    <VisibilityItem guid="guidVcbCommandSet" id="BuildVersionsCommandId" context="UICONTEXT_SolutionHasMultipleProjects" />
    <VisibilityItem guid="guidVcbCommandSet" id="BuildVersionsCommandId" context="UICONTEXT_SolutionBuilding" />
    <VisibilityItem guid="guidVcbCommandSet" id="RebuildVersionsCommandId" context="UICONTEXT_SolutionHasSingleProject" />
    <VisibilityItem guid="guidVcbCommandSet" id="RebuildVersionsCommandId" context="UICONTEXT_SolutionHasMultipleProjects" />
    <VisibilityItem guid="guidVcbCommandSet" id="RebuildVersionsCommandId" context="UICONTEXT_SolutionBuilding" />
    <VisibilityItem guid="guidVcbCommandSet" id="SaveUpdatedVersionsCommandId" context="UICONTEXT_SolutionHasSingleProject" />
    <VisibilityItem guid="guidVcbCommandSet" id="SaveUpdatedVersionsCommandId" context="UICONTEXT_SolutionHasMultipleProjects" />
    <VisibilityItem guid="guidVcbCommandSet" id="SaveUpdatedVersionsCommandId" context="UICONTEXT_SolutionBuilding" />
    <VisibilityItem guid="guidVcbCommandSet" id="SaveVersionsCommandId" context="UICONTEXT_SolutionHasSingleProject" />
    <VisibilityItem guid="guidVcbCommandSet" id="SaveVersionsCommandId" context="UICONTEXT_SolutionHasMultipleProjects" />
    <VisibilityItem guid="guidVcbCommandSet" id="SaveVersionsCommandId" context="UICONTEXT_SolutionBuilding" />
    <VisibilityItem guid="guidVcbCommandSet" id="PrintVersionsCommandId" context="UICONTEXT_SolutionHasSingleProject" />
    <VisibilityItem guid="guidVcbCommandSet" id="PrintVersionsCommandId" context="UICONTEXT_SolutionHasMultipleProjects" />
    <VisibilityItem guid="guidVcbCommandSet" id="PrintVersionsCommandId" context="UICONTEXT_SolutionBuilding" />
  </VisibilityConstraints>
...
```

Just have one file opened and then this won't be a problem anymore.

**Comment by tedebus** [comment]
Hi Guido, thanks for your fast answer! This tool it's fantastic and very useful! 
But there is still a little strange behavior: when you open VS, VCB menu is full, even if you don't have any project opened or selected (Solution Explorer points to the solution root). If you try to select anything (i.e. config menu) from VCB menu strip, it becomes small (after config menu has been closed).
Then, if you open a file in the editor the menu becomes full again, as it should do. But if you close it, the menu remains full while editor is empty. 
It seems that the menu changes based on what you clicked in the solution explorer, rather than on which file is opened in the editor. So if your click on something without double clicking it, VCB will change while file editor is still empty. 
In another situation: if you have a file opened in the editor but you click on the root of the Solution Explorer (not double clicking), the VCB menu will disappear.
It's normal?
I think it's not a great issue, the tool remains very good, but I think these things might be useful for you in future.
