### ISSUE TITLE
Is it possible to use a command line using this extension?

### ISSUE THREAD

**Issue by GuillaumeFagoaga** [GuidoNeele/VersioningControlledBuild#7]
I was using the very useful command line with the VCB add-in ("C:\Program Files (x86)\Versioning Controlled Build\AutoVer.exe"), and I did not find this possibility with this extension. The problem is that the add-in command line is not compatible with Visual Studio 2015 and newer projects.

**Comment by GuidoNeele** [comment]
Hi Guillaume,

Haven't touched the command line tool because I didn't need it at the time. I only ported the bits that were needed to get the add-in to work in VS 2015 and up. 

You could try to do it yourself. The source code of the command line can be downloaded from https://www.codeproject.com/Articles/5851/Versioning-Controlled-Build. Together with the source code from this project you should be able to get it working.

**Comment by GuillaumeFagoaga** [comment]
Thank you very much for your answer.
